### ISSUE TITLE
Proposals

### ISSUE THREAD

**Issue by mikearnaldi** [Matechs-Garage/matechs-effect#1]
To discuss ideas, any library you might think should have a wrapper or any ideas for improvements welcome!

**Comment by mikearnaldi** [comment]
Planned:
- zookeeper
- typeorm
- eventstore
- redis
- express
- apollo (how and to what degree still not certain)

**Comment by mikearnaldi** [comment]
- higer order effect for RPC

**Comment by mikearnaldi** [comment]
- react (extent to be defined, maybe context api for R propagation and Suspance wrappers for execution)

**Comment by sledorze** [comment]
State what is the scope on the support of features beside migration.
Thinking about Queue, Stream, etc.. (some of which appears to be useful for some integrations)

**Comment by mikearnaldi** [comment]
Things that will definately be helpful and will fit easily in the current model are in my opinion:
- Queue
- Ref
- Mutex/Semaphore
- Managed

I though of Streams at least twice but I still have very much unclear what api to expose and to what extend streams should be integrated, if you have an example where streams are a solution we can look into it in details.

**Comment by mikearnaldi** [comment]
As a side note the reason for stating the integrations is to discover better all the needed lower level components and what a good api can look like (for example the RPC integration has helped shaping higher order interpreters)

**Comment by mikearnaldi** [comment]
@sledorze #10 can help on some of the above

**Comment by mikearnaldi** [comment]
Migration to Wave has been merged, next planned is expose apis for Mutex/Semaphore/etc with the proper overloads for env. Also wave has experimental streams implementation that we might leverage too
