### ISSUE TITLE
How to cancel requests that occur too often? 

### ISSUE THREAD

**Issue by Aetet** [Matechs-Garage/matechs-effect#221]
Hi.
Thanks for your huge work at fp-stylish effects.
I haven't enough experience with it. But conception looks very promising.

Library has rich api, but I haven't realize how to solve such case:
I have suggest input. Every time when I type in it, it emits onChange event with 300ms debounce.
I triggers requests to backend. But BE answer with unpredictable speed with 100-500ms. 
That's why our data can stale. To prevent this we can make singletone conditional var, but it looks awkward.

How to deal with in fp style?

**Comment by mikearnaldi** [comment]
Hi @Aetet a repro in code would help the discussion as I currently don't understand your problem.

In general `run` returns a function that when called cancel the running effect, furtermore you can use `fork` to return a fiber that has a `interrupt` effect that when called interrupts the execution.

For discussions you can join our slack channel #matechs via https://fpchat-invite.herokuapp.com

**Comment by Aetet** [comment]
Thanks for invitation!

Here is a [Playground Link](https://www.typescriptlang.org/play/index.html?ssl=1&ssc=1&pln=36&pc=1#code/GYVwdgxgLglg9mABAcwKZQKoGdUCcBiucAtgEICiAFAJSIDeAUIoruiLkmKgO6IAKRYjByVWWOABsAbqkQBeAHz0mzRDigAVGMVRwQUSjXlLGq1WMkzKdRGACGOgFyIARACs4ACyQATOKhdEAF9qAG4VZiCAGkRKAFk7KE8AOlw7MD9iIwBSRABGAAZaACp8gqLwyLCGIIYGUEhYBEQdI1NECXRECD0wKHlEAvCVBuh4JDRMHFwASTBgOEpYHT0oZzAQYgAjPFp25lYodk4efkFhVFFUcWlZRWUzZh6wLH6YMC5cAGFe-rlEADUAJ64Cgw0eKHQ2DwhBIFBoySSqDAlDsxgeEMQMGAsRBfXkcn+70+P1BewimIst1R1UxwQpVUqqhCTNqKkm0Nm80WhSKiM8yNR6P23QQN1QyQkcGQlBcIGmeUcLhidlpwWqKgA9JrEAB1WRYTx6CQ+RB2CTcOwATywiFWAAd9B07K9EPbzjgWNcQBJ+ulTRB0hBUBIsWApHBA00wFEtTrsYgkawAOS2ri8d0kC7sqHTOYLSi86j8wVo+4i57iyXS2XyvAAJiVKrVLJqdVa1SAA)

How to deal with concurrency and correct cancelation for such case?

**Comment by mikearnaldi** [comment]
@Aetet this cose isn't using effect at all, you should convert it first and maybe when converted we can approach the problem

**Comment by Aetet** [comment]
My question is how to convert this imperative code to functional style code.

**Comment by mikearnaldi** [comment]
It would be something like:

```ts
import { T, pipe, Ex } from "@matechs/aio";

const randomWait = T.sync(() => (Math.random() % 10) * 100);
const getUserFromBE = pipe(
  randomWait,
  T.chain((time) => T.delay(T.pure({ name: "john doe" }), time))
);
const me = T.raceFirst(getUserFromBE, getUserFromBE);

T.runToPromiseExit(me).then(
  Ex.foldExit(
    (cause) => {
      console.error(cause);
    },
    (user) => {
      console.log(user);
    }
  )
);
```

**Comment by Aetet** [comment]
What if we don't know how many times getUserFrom BE will be executed? Like infinite stream.

**Comment by mikearnaldi** [comment]
@Aetet if you want to discuss things there is the slack channel, issues are not for this purpose. If you are looking for streams there is the Stream datatype that might help you (again without a code repro is impossible to understand what you mean).
