### ISSUE TITLE
`nestedMap` benchmark is a bit misleading

### ISSUE THREAD

**Issue by masaeedu** [Matechs-Garage/matechs-effect#255]
The `effect` version is simply testing the performance of applying a pure increment function to a `BigInt` a thousand times, without any asynchronicity involved, due to the `Pure` escape hatch in the implementation. You can test this by writing either of the following:

```js
const identity = (() => {
  const map = (v, f) => f(x)
  const pure = x => x
  return { map, pure }
})()

// Given an arbitrary `Apply`, produce an `Applicative`
// https://hackage.haskell.org/package/semigroupoids-5.3.4/docs/Data-Functor-Apply.html#t:MaybeApply
export const maybeApply = (F) => {
  const map = (fv, f) => (fv.tag === IPureTag ? new IPure(f(fv.a)) : F.map(fv, f));
  const pure = (v) => new IPure(v);
  const ap = (fv, ff) =>
    ff.tag === IPureTag
      ? map(fv, ff.a)
      : fv.tag === IPureTag
      ? F.map(ff, (f) => f(fv.a))
      : F.ap(fv, ff);

  return { map, pure, ap };
};

// Try for example maybeApply(QIO) or maybeApply(wave) or whatever
```

Both of these perform about the same as `effect` in the benchmark. In particular, `maybeApply(F)` will perform the same as `effect` regardless of what `F` is (I could write a really poorly performing asynchronicity abstraction and it would still "win" the benchmark if you wrapped it in `maybeApply`). In normal usage, the user's computation is going to have at least one actual asynchronous step that they then map/chain transformations over (otherwise they wouldn't be representing it as an asynchronous effect in the first place).

If the initial `T.pure(BigInt(0))` is replaced with `T.asyncTotal(cb => { cb(BigInt(0)); return () => {}; })` (which is the simplest way I could figure out to work out the performance of actually mapping over an asynchronous effect) and corresponding changes are made to the other benchmarks, the fastest implementation (at least on my system) turns out to be QIO. `effect`'s performance is roughly halved compared to the `T.pure` version, although it still retains a significant lead over `wave`.

---

If you want to try this out yourself, here's the typical result I was observing by running `yarn ts-node -T bench/nestedMap.ts`:

```
yarn run v1.21.1
$ /mnt/code/git/js/experiments/mapbenchmark/matechs-effect/node_modules/.bin/ts-node -T bench/nestedMap.ts
effect x 18,743 ops/sec ±0.96% (84 runs sampled)
wave x 5,964 ops/sec ±1.35% (86 runs sampled)
qio x 11,439 ops/sec ±1.53% (86 runs sampled)
Fastest is effect
Done in 18.26s.
```

Here's the changes I made:

```
diff --git a/packages/effect/bench/nestedMap.ts b/packages/effect/bench/nestedMap.ts
index 8c5b3a92..ba896fde 100644
--- a/packages/effect/bench/nestedMap.ts
+++ b/packages/effect/bench/nestedMap.ts
@@ -8,7 +8,10 @@ const MAX = 1e3;
 const inc = (_: bigint) => _ + BigInt(1);
 
 export const nestedMapWave = (): wave.Wave<never, bigint> => {
-  let io: wave.Wave<never, bigint> = wave.pure(BigInt(0));
+  let io: wave.Wave<never, bigint> = wave.asyncTotal((cb) => {
+    cb(BigInt(0));
+    return () => {};
+  });
   for (let i = 0; i < MAX; i++) {
     io = wave.map(io, inc);
   }
@@ -16,15 +19,18 @@ export const nestedMapWave = (): wave.Wave<never, bigint> => {
 };
 
 export const nestedMapQio = (): QIO<bigint> => {
-  let io: QIO<bigint> = QIO.resolve(BigInt(0));
+  let io: QIO<bigint> = QIO.uninterruptible((cb) => cb(BigInt(0)));
   for (let i = 0; i < MAX; i++) {
     io = QIO.map(io, inc);
   }
   return io;
 };
 
-export const nestedMapEffect = (): T.Sync<bigint> => {
-  let io: T.Sync<bigint> = T.pure(BigInt(0));
+export const nestedMapEffect = (): T.Async<bigint> => {
+  let io: T.Async<bigint> = T.asyncTotal((cb) => {
+    cb(BigInt(0));
+    return () => {};
+  });
   for (let i = 0; i < MAX; i++) {
     io = T.effect.map(io, inc);
   }
```

And here's the typical result I see afterwards:

```
yarn run v1.21.1
$ /mnt/code/git/js/experiments/mapbenchmark/matechs-effect/node_modules/.bin/ts-node -T bench/nestedMap.ts
effect x 9,452 ops/sec ±1.54% (79 runs sampled)
wave x 5,984 ops/sec ±0.98% (86 runs sampled)
qio x 11,491 ops/sec ±1.27% (86 runs sampled)
Fastest is qio
Done in 18.26s.
```

---

I'm not sure what the "simplest" way to turn an arbitrary callback based asynchronous computation into an `effect` or `wave` is, if it's not `asyncTotal` (and hence the updated benchmark is not fair) please let me know.

**Comment by mikearnaldi** [comment]
I will add more benchmarks for the async case, there is a misunderstanding in principle in thinking effect is only for async computations as it supports sync execution and it is intended for usage in both sync and async scenarios.

The banchmark is "fair" for async flows with the exception that you are comparing an interruptable one (asyncTotal) with a non interruptable and the interruptable signature adds a bit of load (not your fault there is no particularly optimized uninterruptable signature in effect, only a region combinator that prevents interruption but that will be again slower)

I would be curious to see a benchmark over a non trivial computation, we can race & win on simple things but my guess (as also stated in readme) is that in a real case all the above performs roughly the same.

I can add that the interruption semanthics and error preservation of effect add overhead so in some flows we are explicitely losing perf to gain safety

**Comment by mikearnaldi** [comment]
Also to add a bit of context in your example you are not adding any async op you are simply wrapping a sync flow into an async combinator but the callback will be executed as soon as the effect computes

**Comment by mikearnaldi** [comment]
Ok I went into details on this, the benchmark difference has definately nothing to do with async stuff happening (if you change in QIO uninterruptable to interruptabile performance double getting in line with pure) but how we manage both interruptability and safety, namely QIO doesn't prevent multiple invokations of the "cb" and doesn't prevent subsequent invocations post-cancellation that will let the fiber continue when it shouldn't:

QIO portion handling the cb https://github.com/tusharmath/qio/blob/master/packages/core/lib/internals/Fiber.ts#L267

We instead do:
```ts
contextSwitch(op: Common.AsyncFn<unknown, unknown>): void {
    let complete = false
    const wrappedCancel = op((status) => {
      if (complete) {
        return
      }
      complete = true
      this.resume(status)
    })
    this.cancelAsync = (cb) => {
      complete = true
      wrappedCancel((...errors) => {
        cb(...errors)
      })
    }
  }
```

So in that case the benchmark is comparing oranges and apples

**Comment by masaeedu** [comment]
> I will add more benchmarks for the async case, there is a misunderstanding in principle in thinking effect is only for async computations as it supports sync execution and it is intended for usage in both sync and async scenarios.

I see, I did indeed misunderstand the purpose of the library. In scenarios where I statically know that no asynchronicity is involved, I would probably use a monad transformer with `Identity` at the bottom, rather than an asynchronicity effect.

> I can add that the interruption semanthics and error preservation of effect add overhead so in some flows we are explicitely losing perf to gain safety

I think this sort of (valid) tradeoff is what a benchmark is supposed to reveal.

> Also to add a bit of context in your example you are not adding any async op you are simply wrapping a sync flow into an async combinator but the callback will be executed as soon as the effect computes

Yes, I understand that. What I'm trying to illustrate is that an actual asynchronous computation will be opaque, and so optimizations that rely on introspecting over the structure of the computations will not be applicable in real world scenarios. Adding actual asynchronicity to the benchmark would be an unnecessary confounding factor, simply putting things behind a callback suffices to level the playing field.

> Ok I went into details on this, the benchmark difference has definately nothing to do with async stuff happening

By "benchmark difference" are you referring to the difference before and after the change I made, or the difference between QIO and the other libraries after the change?

**Comment by mikearnaldi** [comment]
> I see, I did indeed misunderstand the purpose of the library. In scenarios where I statically know that no asynchronicity is involved, I would probably use a monad transformer with Identity at the bottom, rather than an asynchronicity effect.

Valid point for simple scenarios, the library is more intended as an application stack where you will have multiple different flows involved. It somehow resemble the ReaderT architecture and can be used to perform safe dependency injection app-wise.

> Yes, I understand that. What I'm trying to illustrate is that an actual asynchronous computation will be opaque, and so optimizations that rely on introspecting over the structure of the computations will not be applicable in real world scenarios. Adding actual asynchronicity to the benchmark would be an unnecessary confounding factor, simply putting things behind a callback suffices to level the playing field.

Definately get your point, those optimizations are not broadly applicable but there are scenarios where they are triggered, clearly not in a chain of async stuff (also tbh when you start to have async things most of the time is spent on waiting for the result on the small perf differences are no longer relevant)

> By "benchmark difference" are you referring to the difference before and after the change I made, or the difference between QIO and the other libraries after the change?

I am referring to the difference before and after your change and actually to the even greater difference when changing `uninterruptable` to `interruptable` in QIO, if you do that you will see the perf of QIO doubling even beating the optimized case. Simply because uninterruptable is implemented in terms of interruptable and has more steps the code has to go through.

On a final point I am actually still analyzing QIO and trying to understand what type of optimization gets triggered in node that optimize the loop of it's fiber, reason being the op count in QIO is much greater, even has a yield strategy that adds a number of operations before the loop starts to voluntarily delay execution

**Comment by mikearnaldi** [comment]
I take it back, the code I was referring to as much faster is:
```ts
export const nestedMapQio = (): QIO<bigint> => {
  let io: QIO<bigint> = QIO.interruptible((cb) => {
    cb(BigInt(0))
    return {
      cancel: () => {

      }
    }
  })
  for (let i = 0; i < MAX; i++) {
    io = QIO.map(io, inc)
  }
  return io
}
```

But the reason it is faster in banchmark is that it actually throws an exception because the callback is assumed not to be called in the same pass of the event loop (generates a circular reference on the id of the cancellation list)

**Comment by mikearnaldi** [comment]
The optimizations in question have been removed in https://github.com/Matechs-Garage/matechs-effect/commit/dc107593c011a8371546022e1fc4aad6ae8ba83c 

The reason is not that they are hardly triggered but that if triggered can lead to stack unsafety, we have also decided to no longer expose any "dumb" benchmark in the repo as the feature set of each library is different and only real-life benchmarks can be relevant to the purpose. 

Thanks very much for raising this issue as it spotted a dumb decision taken to win a dumb race!
