### ISSUE TITLE
Align effect.filterOrElse with either.filterOrElse

### ISSUE THREAD

**Issue by jsmacka** [Matechs-Garage/matechs-effect#273]
**Is your feature request related to a problem? Please describe.**
`filterOrElse` seems to have a different logic for `Effect` and `Managed` than it does for `Either`. It would be less confusing if that was not the case. 

**Describe the solution you'd like**
When the predicate returns true I would expect to end up in the successful rather than the unsuccessful case.

In core/src/Effect/index.ts I would like to see:
```
export const filterOrElse: {
  <E, A, B extends A>(refinement: Refinement<A, B>, onFalse: (a: A) => E): <S, R>(
    ma: Effect<S, R, E, A>
  ) => Effect<S, R, E, B>
  <E, A>(predicate: Predicate<A>, onFalse: (a: A) => E): <S, R>(
    ma: Effect<S, R, E, A>
  ) => Effect<S, R, E, A>
} = <E, A>(predicate: Predicate<A>, onFalse: (a: A) => E) => <S, R>(
  ma: Effect<S, R, E, A>
): Effect<S, R, E, A> =>
  chain_(ma, (a) => (predicate(a) ? completed(done(a)) : completed(raise(onFalse(a)))))
// instead of chain_(ma, (a) => (predicate(a) ? completed(raise(onFalse(a))) : completed(done(a))))
```

and in core/src/Managed/index.ts:
```
export const filterOrElse: {
  <E, A, B extends A>(refinement: Refinement<A, B>, onFalse: (a: A) => E): <S, R>(
    ma: Managed<S, R, E, A>
  ) => Managed<S, R, E, B>
  <E, A>(predicate: Predicate<A>, onFalse: (a: A) => E): <S, R>(
    ma: Managed<S, R, E, A>
  ) => Managed<S, R, E, A>
} = <E, A>(predicate: Predicate<A>, onFalse: (a: A) => E) => <S, R>(
  ma: Managed<S, R, E, A>
): Managed<S, R, E, A> =>
  chain_(ma, (a) =>
    predicate(a)
      ? encaseEffect(T.completed(done(a)))
      : encaseEffect(T.completed(raise(onFalse(a))))
  )
```

Compare to core/src/Either/index.ts:
```
export const filterOrElse: {
  <E, A, B extends A>(refinement: Refinement<A, B>, onFalse: (a: A) => E): <E2>(
    ma: Either<E2, A>
  ) => Either<E | E2, B>
  <E, A>(predicate: Predicate<A>, onFalse: (a: A) => E): <E2>(
    ma: Either<E2, A>
  ) => Either<E | E2, A>
} = <E, A>(predicate: Predicate<A>, onFalse: (a: A) => E) => (
  ma: Either<E, A>
): Either<E, A> => chain_(ma, (a) => (predicate(a) ? right(a) : left(onFalse(a))))
```

**Describe alternatives you've considered**
I considered the possibility that my brain was overwhelmed with Booleans as it sometimes does and that this was a non-issue after all. Apart from that, nothing came to mind. 

**Additional context**
This led me to leave out `filterOrElse` in todays presentation of `Effect` (using chain instead). I think that might have been a good thing insofar as keeping information overload down...

**Comment by jsmacka** [comment]
Opened a pull request to solve this: #274

**Comment by mikearnaldi** [comment]
@jsmacka thanks a lot for this, definitely a mistake!

**Comment by jsmacka** [comment]
Phew, thank you - that soothes my mind ^^

**Comment by mikearnaldi** [comment]
published in https://github.com/Matechs-Garage/matechs-effect/commit/a14e578b9cdd3f187524e61799ffa9e85db016c8
