### ISSUE TITLE
Early program exit on timeout unref

### ISSUE THREAD

**Issue by qlonik** [Matechs-Garage/matechs-effect#283]
I stumbled on the code from 3rd party library, which calls `setTimeout().unref()` in their async call. The unref calls create a timer which allows nodejs even loop to exit if there is no other work scheduled. This behaviour makes the effect exit early when there are unrefs in async effects.

Here is a repo using current version of effect:
```typescript
import * as T from "@matechs/core/Effect";
import { pipe } from "@matechs/core/Function";

const log = <A extends unknown[]>(...x: A): T.Sync<void> => T.sync(() => console.log(...x));

pipe(
  log("before main"),
  T.apSecond(
    T.uninterruptibleAsyncTotal<void>((next) => {
      const t = setTimeout(() => next(undefined), 0);
      t.unref();
    })
  ),
  T.apSecond(log("after main")),
  T.runToPromiseExit,
  (p) => p.then(console.log)
);
```

Here is a repro using next version of effect:
```typescript
import { pipe } from "@matechs/core/Function";
import * as T from "@matechs/core/next/Effect";

const log = <A extends unknown[]>(...x: A): T.Sync<void> => T.effectTotal(() => console.log(...x));

pipe(
  log("before main"),
  T.zipSecond(
    T.effectAsync((next) => {
      const t = setTimeout(() => next(T.succeedNow(undefined)), 0);
      t.unref();
    })
  ),
  T.zipSecond(log("after main")),
  T.runPromiseExit,
  (p) => p.then(console.log)
);
```

One idea I have off the top of my head is the solution similar to the one done in the original library: they set very large `setInterval` during runtime preventing app exit, even if they call unref. We could do something similar, but on a smaller scale: we could setup very large `setInterval` before executing any async task. We might have many intervals this way, but maybe we could somehow have only one interval as long as there at least one async task.

**Comment by mikearnaldi** [comment]
I am unsure if this is actually expected behaviour, in the "next" we could add this interval trick easily (actually the fibers are already tracked so it would be a matter of just setting the interval)

**Comment by mikearnaldi** [comment]
@qlonik I am trying this on next, similar could be backported, what do you think?
https://github.com/Matechs-Garage/matechs-effect/commit/1954c0ae540ee5e921caf2095b1c0e19bf98c6ef

**Comment by qlonik** [comment]
I'm not sure. This is a pretty obscure error, and it is fixed by updating the offending package. I'm not sure how frequently doing an unref on timeout is going to be encountered.

Is it a lot of effort? If not a lot, maybe it could be ported, otherwise it is probably okay if it is left out.

**Comment by mikearnaldi** [comment]
I am still trying to see if I can include the setup of the interval in the root supervisor rather than having a specific tracer (backporting should not be an issue)
